services:
  # 1. El Microservicio Mock (El final del camino)
  mock-api:
    build: ./api
    expose:
      - "3000"
    # No exponemos puertos a la máquina host, está aislado en la red interna de Docker

  # 2. El API Gateway Interno (YARP + .NET 8)
  gateway:
    build:
      context: ./gateway/Cosmos.Gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mock-api

  # 3. El Túnel de Cloudflare (El Muro Exterior Zero Trust)
  cloudflared:
    image: cloudflare/cloudflared:latest
    # Configuramos un "Quick Tunnel" gratuito que apuntará a nuestro Gateway Interno
    command: tunnel --url http://gateway:8080
    depends_on:
      - gateway
