events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;

        location /api/ {
            # En el mundo real, aquí iría la validación del JWT contra Azure AD
            # Para la PoC, simulamos que el token fue validado con éxito
            # e inyectamos el Trusted Header hacia el microservicio
            
            proxy_set_header X-Cosmos-UserId "User-AB-12345";
            proxy_set_header X-Cosmos-Tenant "Sincosoft-Dev";
            
            # Enrutar al microservicio interno (usamos el nombre del servicio Docker)
            proxy_pass http://mock-api:3000/api/;
        }
    }
}
